/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenkopi;

import java.awt.Frame;
import javax.swing.JFrame;
import com.mysql.jdbc.Connection;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author fajarega
 */
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
public class formproduk extends javax.swing.JFrame {
Connection koneksi;
    /**
     * Creates new form formproduk
     */
    public formproduk() {
        initComponents();
        koneksi = (Connection) databaseconnection.getKoneksi("localhost","3306","root","","db_industri");
        tampilproduk();
    }
    private DefaultTableModel tabmode;
    private void tampilproduk(){
        Object[] baris = {"No","Id produk","Nama produk","Harga produk","Jumlah produk","Stok produk","Status produksi"};
        
        tabmode = new DefaultTableModel(null,baris);
        tabmode.setRowCount(0);
         
         try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM t_produk";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()){
                String id_produk = rs.getString("t_produk.id_produk");
                String nama_produk = rs.getString("t_produk.nama_produk");
                String harga_produk = rs.getString("t_produk.harga_produk");
                String jumlah_produk = rs.getString("t_produk.jumlah_produk");
                String stok_produk = rs.getString("t_produk.stok_produk");
                String status_produksi = rs.getString("t_produk.status_produksi");
                String[] data = {no+"",id_produk,nama_produk,harga_produk,jumlah_produk,stok_produk,status_produksi};
                no++;
                tabmode.addRow(data);
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
         table_produk.setModel(tabmode);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Btnrefresh = new javax.swing.JButton();
        BtnRpegawai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        Id_produk = new javax.swing.JTextField();
        Nama_produk = new javax.swing.JTextField();
        Harga_produk = new javax.swing.JTextField();
        Cbstatus_produksi = new javax.swing.JComboBox<>();
        Stok_produk = new javax.swing.JTextField();
        Btn_simpan = new javax.swing.JButton();
        b_Update = new javax.swing.JButton();
        b_Delete = new javax.swing.JButton();
        b_Reset = new javax.swing.JButton();
        Stok_produk1 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_produk = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Fhome = new javax.swing.JMenuItem();
        Flogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Fexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Dpegawai = new javax.swing.JMenuItem();
        Dpenggajian = new javax.swing.JMenuItem();
        Dperlengkapan = new javax.swing.JMenuItem();
        Dproduk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Rpegawai = new javax.swing.JMenuItem();
        Rpenggajian = new javax.swing.JMenuItem();
        Rperlengkapan = new javax.swing.JMenuItem();
        Rproduk = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Hinfo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Ateam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jToolBar1.setRollover(true);

        Btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/002-refresh.png"))); // NOI18N
        Btnrefresh.setFocusable(false);
        Btnrefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnrefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnrefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(Btnrefresh);

        BtnRpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/people-4.png"))); // NOI18N
        BtnRpegawai.setFocusable(false);
        BtnRpegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRpegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnRpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRpegawaiActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnRpegawai);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MANAGE PRODUK\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        a.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        a.setText("ID PRODUK");

        c.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        c.setText(" Nama Produk");

        f.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        f.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f.setText("Harga Produk");

        j.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        j.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j.setText("Status Produksi");

        l.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        l.setText("Stok Produk");

        Id_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_produkActionPerformed(evt);
            }
        });

        Cbstatus_produksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Tersedia", "Habis", " " }));

        Btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/16 Pixel/add-contact.png"))); // NOI18N
        Btn_simpan.setText("Tambah");
        Btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_simpanActionPerformed(evt);
            }
        });

        b_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save-16x16.png"))); // NOI18N
        b_Update.setText("Update");
        b_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UpdateActionPerformed(evt);
            }
        });

        b_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete-16x16.png"))); // NOI18N
        b_Delete.setText("Delete");
        b_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_DeleteActionPerformed(evt);
            }
        });

        b_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        b_Reset.setText("Reset");
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Jumlah Produk");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(Id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(Harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbstatus_produksi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Stok_produk, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                .addComponent(Stok_produk1)))))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_simpan)
                            .addComponent(b_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(Id_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(Nama_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f)
                            .addComponent(Harga_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1)
                    .addComponent(Stok_produk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l)
                    .addComponent(Stok_produk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j)
                    .addComponent(Cbstatus_produksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        table_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id produk", "Nama produk", "Harga produk", "Jumlah produk", "Stok produk", "Status produksi"
            }
        ));
        table_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_produkMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_produk);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(309, 309, 309)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE)))
        );

        jMenu1.setText("File");

        Fhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/konfigurasi_univ.png"))); // NOI18N
        Fhome.setText("Home");
        Fhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Fhome);

        Flogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/operator.png"))); // NOI18N
        Flogout.setText("Logout");
        Flogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Flogout);
        jMenu1.add(jSeparator1);

        Fexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cross.png"))); // NOI18N
        Fexit.setText("Exit");
        Fexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FexitActionPerformed(evt);
            }
        });
        jMenu1.add(Fexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        Dpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpegawai.setText("Data Pegawai");
        Dpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(Dpegawai);

        Dpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpenggajian.setText("Data Penggajian");
        Dpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpenggajianActionPerformed(evt);
            }
        });
        jMenu2.add(Dpenggajian);

        Dperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dperlengkapan.setText("Data Perlengkapan");
        Dperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DperlengkapanActionPerformed(evt);
            }
        });
        jMenu2.add(Dperlengkapan);

        Dproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dproduk.setText("Data Produk");
        jMenu2.add(Dproduk);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Report");

        Rpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpegawai.setText("Pegawai");
        Rpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpegawaiActionPerformed(evt);
            }
        });
        jMenu3.add(Rpegawai);

        Rpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpenggajian.setText("Penggajian");
        Rpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpenggajianActionPerformed(evt);
            }
        });
        jMenu3.add(Rpenggajian);

        Rperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rperlengkapan.setText("Perlengkapan");
        Rperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RperlengkapanActionPerformed(evt);
            }
        });
        jMenu3.add(Rperlengkapan);

        Rproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rproduk.setText("Produk");
        Rproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprodukActionPerformed(evt);
            }
        });
        jMenu3.add(Rproduk);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        Hinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        Hinfo.setText("Info");
        Hinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinfoActionPerformed(evt);
            }
        });
        jMenu4.add(Hinfo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("About");

        Ateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/mutasipegawai.png"))); // NOI18N
        Ateam.setText("Team");
        Ateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AteamActionPerformed(evt);
            }
        });
        jMenu5.add(Ateam);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void FhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FhomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        this.dispose();
    }//GEN-LAST:event_FhomeActionPerformed

    private void DperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DperlengkapanActionPerformed
        // TODO add your handling code here:
        new formperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_DperlengkapanActionPerformed

    private void RpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpenggajianActionPerformed
        // TODO add your handling code here:
        new lapgaji().show();
        this.dispose();
    }//GEN-LAST:event_RpenggajianActionPerformed

    private void RperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RperlengkapanActionPerformed
        // TODO add your handling code here:
        new lapperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_RperlengkapanActionPerformed

    private void FlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlogoutActionPerformed
        // TODO add your handling code here:
        new login().show();
        this.dispose();
    }//GEN-LAST:event_FlogoutActionPerformed

    private void FexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FexitActionPerformed

    private void DpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpegawaiActionPerformed
        // TODO add your handling code here:
        new formkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_DpegawaiActionPerformed

    private void DpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpenggajianActionPerformed
        // TODO add your handling code here:
        new formgaji().show();
        this.dispose();
    }//GEN-LAST:event_DpenggajianActionPerformed

    private void RpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_RpegawaiActionPerformed

    private void RprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprodukActionPerformed
        // TODO add your handling code here:
        new lapproduk().show();
        this.dispose();
    }//GEN-LAST:event_RprodukActionPerformed

    private void HinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinfoActionPerformed
        // TODO add your handling code here:
        new info().show();
        this.dispose();
    }//GEN-LAST:event_HinfoActionPerformed

    private void AteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AteamActionPerformed
        // TODO add your handling code here:
        new team().show();
        this.dispose();
    }//GEN-LAST:event_AteamActionPerformed

    private void BtnRpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_BtnRpegawaiActionPerformed

    private void BtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnrefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnrefreshActionPerformed

    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
        reset();
    }//GEN-LAST:event_b_ResetActionPerformed
    int baris;
    private void b_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_DeleteActionPerformed
        // TODO add your handling code here:
        String idWhoWantToBeDelete = table_produk.getValueAt(baris, 1).toString();
        try {
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM t_produk WHERE id_produk = '"+idWhoWantToBeDelete+"';";
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                tabmode.getDataVector().removeAllElements();
                tampilproduk();
                reset();
            }
            koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_b_DeleteActionPerformed

    private void b_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UpdateActionPerformed
    EditData();
    tampilproduk();
    reset();
    }//GEN-LAST:event_b_UpdateActionPerformed
    public void EditData()
    {
        String id_produk = Id_produk.getText();
        String nama_produk = Nama_produk.getText();
        String harga_produk = Harga_produk.getText();
        String jumlah_produk = Stok_produk1.getText();
        String stok_produk = Stok_produk.getText();
        String status_produksi = Cbstatus_produksi.getSelectedItem().toString();
        
        try
        {
            Statement stmt = koneksi.createStatement();
            String query = "UPDATE t_produk SET nama_produk='"+nama_produk+"',"+"harga_produk='"+harga_produk+"',"+"jumlah_produk='"+jumlah_produk+"',"+"stok_produk='"+stok_produk+"',"+"status_produksi='"+status_produksi+"' WHERE id_produk = '"+id_produk+"'";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1)
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
        }
    }
    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed

        String id_produk = Id_produk.getText();
        String nama_produk = Nama_produk.getText();
        String harga_produk = Harga_produk.getText();
        String jumlah_produk = Stok_produk1.getText();
        String stok_produk = Stok_produk.getText();
        String status_produksi = Cbstatus_produksi.getSelectedItem().toString();

        try{
            Statement stmt = koneksi.createStatement();
            String query = "INSERT INTO t_produk"+ "(id_produk,nama_produk,harga_produk,jumlah_produk,stok_produk,status_produksi)"+"VALUES('"+id_produk+"', '"+nama_produk+"', '"+harga_produk+"', '"+jumlah_produk+"', '"+stok_produk+"', '"+status_produksi+"')";
            System.out.print(query);
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
                tampilproduk();
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal Dimasukkan");
                reset();
            }
            koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database");
            reset();
        }
    }//GEN-LAST:event_Btn_simpanActionPerformed

    private void Id_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_produkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_produkActionPerformed
public void reset()
    {
        Id_produk.setText("");
        Nama_produk.setText("");
        Harga_produk.setText("");
        Stok_produk1.setText("");
        Stok_produk.setText("");
        Cbstatus_produksi.setSelectedIndex(0);
    }
    private void table_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_produkMouseClicked
        // TODO add your handling code here:
        baris = table_produk.getSelectedRow();
        Id_produk.setText(table_produk.getValueAt(baris,1).toString());
        Nama_produk.setText(table_produk.getValueAt(baris,2).toString());
        Harga_produk.setText(table_produk.getValueAt(baris,3).toString());
        Stok_produk1.setText(table_produk.getValueAt(baris,4).toString());
        Stok_produk.setText(table_produk.getValueAt(baris,5).toString());
        Cbstatus_produksi.setSelectedItem(table_produk.getValueAt(baris,6).toString());

    }//GEN-LAST:event_table_produkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formproduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formproduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ateam;
    private javax.swing.JButton BtnRpegawai;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JButton Btnrefresh;
    private javax.swing.JComboBox<String> Cbstatus_produksi;
    private javax.swing.JMenuItem Dpegawai;
    private javax.swing.JMenuItem Dpenggajian;
    private javax.swing.JMenuItem Dperlengkapan;
    private javax.swing.JMenuItem Dproduk;
    private javax.swing.JMenuItem Fexit;
    private javax.swing.JMenuItem Fhome;
    private javax.swing.JMenuItem Flogout;
    private javax.swing.JTextField Harga_produk;
    private javax.swing.JMenuItem Hinfo;
    private javax.swing.JTextField Id_produk;
    private javax.swing.JTextField Nama_produk;
    private javax.swing.JMenuItem Rpegawai;
    private javax.swing.JMenuItem Rpenggajian;
    private javax.swing.JMenuItem Rperlengkapan;
    private javax.swing.JMenuItem Rproduk;
    private javax.swing.JTextField Stok_produk;
    private javax.swing.JTextField Stok_produk1;
    private javax.swing.JLabel a;
    private javax.swing.JButton b_Delete;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Update;
    private javax.swing.JLabel c;
    private javax.swing.JLabel f;
    private javax.swing.JLabel j;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel l;
    private javax.swing.JLabel l1;
    private javax.swing.JTable table_produk;
    // End of variables declaration//GEN-END:variables
}
