/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenkopi;

import java.awt.Frame;
import javax.swing.JFrame;
import com.mysql.jdbc.Connection;
import java.awt.print.PrinterException;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author fajarega
 */
import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.table.TableModel;
public class formgaji extends javax.swing.JFrame {
Connection koneksi;
    /**
     * Creates new form formgaji
     */
    public formgaji() {
        initComponents();
        koneksi = (Connection) databaseconnection.getKoneksi("localhost","3306","root","","db_industri");
        tampilgaji();
    }
    
    private DefaultTableModel tabmode;
    private void tampilgaji(){
        Object[] baris = {"No","Nik","Nama karyawan","Jabatan","Gaji pokok","Tunjangan","Uang makan","Bonus","Potongan","Gaji bersih"};
        
        tabmode = new DefaultTableModel(null,baris);
        tabmode.setRowCount(0);
         
         try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM t_penggajian";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()){
                String Nik = rs.getString("t_penggajian.nik");
                String Nama_karyawan = rs.getString("t_penggajian.nama_karyawan");
                String Jabatan = rs.getString("t_penggajian.jabatan");
                String Gaji_Pokok = rs.getString("t_penggajian.gaji_pokok");
                String Tunjangan = rs.getString("t_penggajian.tunjangan");
                String Uang_makan = rs.getString("t_penggajian.uang_makan");
                String Bonus = rs.getString("t_penggajian.bonus");
                String Potongan = rs.getString("t_penggajian.potongan");
                String Gaji_bersih = rs.getString("t_penggajian.gaji_bersih");
                String[] data = {no+"",Nik,Nama_karyawan,Jabatan,Gaji_Pokok,Tunjangan,Uang_makan,Bonus,Potongan,Gaji_bersih};
                no++;
                tabmode.addRow(data);
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
         table_gaji.setModel(tabmode);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Btnrefresh = new javax.swing.JButton();
        BtnRpegawai = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        Nik = new javax.swing.JTextField();
        nama_karyawan = new javax.swing.JTextField();
        tunjangan = new javax.swing.JTextField();
        Cbjabatan = new javax.swing.JComboBox<>();
        gaji_pokok = new javax.swing.JTextField();
        Btn_simpan = new javax.swing.JButton();
        b_Update = new javax.swing.JButton();
        b_Delete = new javax.swing.JButton();
        b_Reset = new javax.swing.JButton();
        f1 = new javax.swing.JLabel();
        uang_makan = new javax.swing.JTextField();
        j1 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        gaji_bersih = new javax.swing.JTextField();
        potongan = new javax.swing.JTextField();
        bonus = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_gaji = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Fhome = new javax.swing.JMenuItem();
        Flogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Fexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Dpegawai = new javax.swing.JMenuItem();
        Dpenggajian = new javax.swing.JMenuItem();
        Dperlengkapan = new javax.swing.JMenuItem();
        Dproduk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Rpegawai = new javax.swing.JMenuItem();
        Rpenggajian = new javax.swing.JMenuItem();
        Rperlengkapan = new javax.swing.JMenuItem();
        Rproduk = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Hinfo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Ateam = new javax.swing.JMenuItem();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jFrame1formWindowOpened(evt);
            }
        });

        jMenu6.setText("File");

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/konfigurasi_univ.png"))); // NOI18N
        jMenuItem14.setText("Home");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/operator.png"))); // NOI18N
        jMenuItem15.setText("Logout");
        jMenu6.add(jMenuItem15);
        jMenu6.add(jSeparator2);

        jMenuItem16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cross.png"))); // NOI18N
        jMenuItem16.setText("Exit");
        jMenu6.add(jMenuItem16);

        jMenuBar2.add(jMenu6);

        jMenu7.setText("Form");

        jMenuItem17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        jMenuItem17.setText("Data Pegawai");
        jMenu7.add(jMenuItem17);

        jMenuItem18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        jMenuItem18.setText("Data Penggajian");
        jMenu7.add(jMenuItem18);

        jMenuItem19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        jMenuItem19.setText("Data Perlengkapan");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem19);

        jMenuItem20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        jMenuItem20.setText("Data Produk");
        jMenu7.add(jMenuItem20);

        jMenuBar2.add(jMenu7);

        jMenu8.setText("Report");

        jMenuItem21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        jMenuItem21.setText("Pegawai");
        jMenu8.add(jMenuItem21);

        jMenuItem22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        jMenuItem22.setText("Penggajian");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem22);

        jMenuItem23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        jMenuItem23.setText("Perlengkapan");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem23);

        jMenuItem24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        jMenuItem24.setText("Produk");
        jMenu8.add(jMenuItem24);

        jMenuBar2.add(jMenu8);

        jMenu9.setText("Help");

        jMenuItem25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        jMenuItem25.setText("Info");
        jMenu9.add(jMenuItem25);

        jMenuBar2.add(jMenu9);

        jMenu10.setText("About");

        jMenuItem26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/mutasipegawai.png"))); // NOI18N
        jMenuItem26.setText("Team");
        jMenu10.add(jMenuItem26);

        jMenuBar2.add(jMenu10);

        jFrame1.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1232, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 503, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenu11.setText("jMenu11");

        jMenu12.setText("File");
        jMenuBar3.add(jMenu12);

        jMenu13.setText("Edit");
        jMenuBar3.add(jMenu13);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jToolBar1.setRollover(true);

        Btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/002-refresh.png"))); // NOI18N
        Btnrefresh.setFocusable(false);
        Btnrefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnrefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnrefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(Btnrefresh);

        BtnRpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/people-4.png"))); // NOI18N
        BtnRpegawai.setFocusable(false);
        BtnRpegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRpegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnRpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRpegawaiActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnRpegawai);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MANAGE GAJI\n\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        a.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        a.setText("NIK");

        c.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c.setText("Nama Karyawan");

        f.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        f.setText("Tunjangan");

        j.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        j.setText("Jabatan");

        l.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        l.setText("Gaji Pokok");

        Nik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NikActionPerformed(evt);
            }
        });

        Cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "General Manajer", "Direktur", "Supervisor", "HRD", "Staff", "Sales", "Buruh", "Sopir", "Security" }));

        Btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/16 Pixel/add-contact.png"))); // NOI18N
        Btn_simpan.setText("Tambah");
        Btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_simpanActionPerformed(evt);
            }
        });

        b_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save-16x16.png"))); // NOI18N
        b_Update.setText("Update");
        b_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UpdateActionPerformed(evt);
            }
        });

        b_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete-16x16.png"))); // NOI18N
        b_Delete.setText("Delete");
        b_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_DeleteActionPerformed(evt);
            }
        });

        b_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        b_Reset.setText("Reset");
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });

        f1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        f1.setText("Uang Makan");

        j1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        j1.setText("Bonus");

        a1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        a1.setText("Potongan");

        c1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        c1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c1.setText("Gaji Bersih");

        potongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potonganActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(a, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(Nik, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(gaji_pokok))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(uang_makan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(c)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(a1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(potongan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(c1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(gaji_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(Nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(nama_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a1)
                            .addComponent(potongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c1)
                            .addComponent(gaji_bersih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j)
                            .addComponent(Cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l)
                            .addComponent(gaji_pokok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tunjangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(f1)
                            .addComponent(uang_makan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j1)
                            .addComponent(bonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_simpan)
                            .addComponent(b_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );

        table_gaji.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nik", "Nama karyawan", "Jabatan", "Gaji pokok", "Tunjangan", "Uang makan", "Bonus", "Potongan", "Gaji bersih"
            }
        ));
        table_gaji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_gajiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_gaji);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu1.setText("File");

        Fhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/konfigurasi_univ.png"))); // NOI18N
        Fhome.setText("Home");
        Fhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Fhome);

        Flogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/operator.png"))); // NOI18N
        Flogout.setText("Logout");
        Flogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Flogout);
        jMenu1.add(jSeparator1);

        Fexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cross.png"))); // NOI18N
        Fexit.setText("Exit");
        Fexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FexitActionPerformed(evt);
            }
        });
        jMenu1.add(Fexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        Dpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpegawai.setText("Data Pegawai");
        Dpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(Dpegawai);

        Dpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpenggajian.setText("Data Penggajian");
        jMenu2.add(Dpenggajian);

        Dperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dperlengkapan.setText("Data Perlengkapan");
        Dperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DperlengkapanActionPerformed(evt);
            }
        });
        jMenu2.add(Dperlengkapan);

        Dproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dproduk.setText("Data Produk");
        Dproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DprodukActionPerformed(evt);
            }
        });
        jMenu2.add(Dproduk);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Report");

        Rpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpegawai.setText("Pegawai");
        Rpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpegawaiActionPerformed(evt);
            }
        });
        jMenu3.add(Rpegawai);

        Rpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpenggajian.setText("Penggajian");
        Rpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpenggajianActionPerformed(evt);
            }
        });
        jMenu3.add(Rpenggajian);

        Rperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rperlengkapan.setText("Perlengkapan");
        Rperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RperlengkapanActionPerformed(evt);
            }
        });
        jMenu3.add(Rperlengkapan);

        Rproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rproduk.setText("Produk");
        Rproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprodukActionPerformed(evt);
            }
        });
        jMenu3.add(Rproduk);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        Hinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        Hinfo.setText("Info");
        Hinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinfoActionPerformed(evt);
            }
        });
        jMenu4.add(Hinfo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("About");

        Ateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/mutasipegawai.png"))); // NOI18N
        Ateam.setText("Team");
        Ateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AteamActionPerformed(evt);
            }
        });
        jMenu5.add(Ateam);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jFrame1formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrame1formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_jFrame1formWindowOpened

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here: 
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void FhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FhomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        this.dispose();
    }//GEN-LAST:event_FhomeActionPerformed

    private void DperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DperlengkapanActionPerformed
        // TODO add your handling code here:
        new formperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_DperlengkapanActionPerformed

    private void RpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpenggajianActionPerformed
        // TODO add your handling code here:
        new lapgaji().show();
        this.dispose();
    }//GEN-LAST:event_RpenggajianActionPerformed

    private void RperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RperlengkapanActionPerformed
        // TODO add your handling code here:
        new lapperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_RperlengkapanActionPerformed

    private void FlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlogoutActionPerformed
        // TODO add your handling code here:
        new login().show();
        this.dispose();
    }//GEN-LAST:event_FlogoutActionPerformed

    private void FexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FexitActionPerformed

    private void DpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpegawaiActionPerformed
        // TODO add your handling code here:
        new formkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_DpegawaiActionPerformed

    private void DprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DprodukActionPerformed
        // TODO add your handling code here:
        new formproduk().show();
        this.dispose();
    }//GEN-LAST:event_DprodukActionPerformed

    private void RpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_RpegawaiActionPerformed

    private void RprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprodukActionPerformed
        // TODO add your handling code here:
        new lapproduk().show();
        this.dispose();
    }//GEN-LAST:event_RprodukActionPerformed

    private void HinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinfoActionPerformed
        // TODO add your handling code here:
        new info().show();
        this.dispose();
    }//GEN-LAST:event_HinfoActionPerformed

    private void AteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AteamActionPerformed
        // TODO add your handling code here:
        new team().show();
        this.dispose();
    }//GEN-LAST:event_AteamActionPerformed

    private void BtnRpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_BtnRpegawaiActionPerformed

    private void BtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnrefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnrefreshActionPerformed

    private void NikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NikActionPerformed
    public void EditData()
    {
        String nik = Nik.getText();
        String nama = nama_karyawan.getText();
        String jabatan = Cbjabatan.getSelectedItem().toString();
        String Gaji_pokok = gaji_pokok.getText();
        String Tunjangan = tunjangan.getText();
        String Uang_makan = uang_makan.getText();
        String Bonus = bonus.getText();
        String Potongan = potongan.getText();
        String Gaji_bersih = gaji_bersih.getText();
        
        try
        {
            Statement stmt = koneksi.createStatement();
            String query = "UPDATE t_penggajian SET "+ "uang_makan='"+Uang_makan+"',"+"nama_karyawan='"+nama+"',"+"jabatan='"+jabatan+"',"+"gaji_pokok='"+Gaji_pokok+"',"+"tunjangan='"+Tunjangan+"',"+"bonus='"+Bonus+"',"+"potongan='"+Potongan+"',"+"gaji_bersih='"+Gaji_bersih+"' "+ "WHERE NIK = '"+nik+"'";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1)
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
        }
    }
    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed

        String nik = Nik.getText();
        String nama = nama_karyawan.getText();
        String jabatan = Cbjabatan.getSelectedItem().toString();
        String Gaji_pokok = gaji_pokok.getText();
        String Tunjangan = tunjangan.getText();
        String Uang_makan = uang_makan.getText();
        String Bonus = bonus.getText();
        String Potongan = potongan.getText();
        String Gaji_bersih = gaji_bersih.getText();

        try{
            Statement stmt = koneksi.createStatement();
            String query = "INSERT INTO t_penggajian"+ "(nik,nama_karyawan,jabatan,gaji_pokok,tunjangan,uang_makan,bonus,potongan,gaji_bersih)"+"VALUES('"+nik+"', '"+nama+"', '"+jabatan+"', '"+Gaji_pokok+"', '"+Tunjangan+"', '"+Uang_makan+"', '"+Bonus+"', '"+Potongan+"', '"+Gaji_bersih+"')";
            System.out.print(query);
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
                tampilgaji();
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal Dimasukkan");
                reset();
            }
            koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database");
            reset();
        }
    }//GEN-LAST:event_Btn_simpanActionPerformed

    private void b_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UpdateActionPerformed
    EditData();
    tampilgaji();
    reset();
    }//GEN-LAST:event_b_UpdateActionPerformed
int baris;
    private void b_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_DeleteActionPerformed
        // TODO add your handling code here:
        String idWhoWantToBeDelete = table_gaji.getValueAt(baris, 1).toString();
        try {
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM t_penggajian WHERE nik = '"+idWhoWantToBeDelete+"';";
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                tabmode.getDataVector().removeAllElements();
                tampilgaji();
                reset();
            }
            koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_b_DeleteActionPerformed

    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
        reset();
    }//GEN-LAST:event_b_ResetActionPerformed

        public void reset()
    {
        Nik.setText("");
        nama_karyawan.setText("");
        Cbjabatan.setSelectedIndex(0);
        gaji_pokok.setText("");
        tunjangan.setText("");
        potongan.setText("");
        gaji_bersih.setText("");
    }
    
    private void table_gajiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_gajiMouseClicked
        // TODO add your handling code here:
        baris = table_gaji.getSelectedRow();
        Nik.setText(table_gaji.getValueAt(baris,1).toString());
        nama_karyawan.setText(table_gaji.getValueAt(baris,2).toString());
        Cbjabatan.setSelectedItem(table_gaji.getValueAt(baris,3).toString());
        gaji_pokok.setText(table_gaji.getValueAt(baris,4).toString());
        tunjangan.setText(table_gaji.getValueAt(baris,5).toString());
        potongan.setText(table_gaji.getValueAt(baris,7).toString());
        gaji_bersih.setText(table_gaji.getValueAt(baris,9).toString());
    }//GEN-LAST:event_table_gajiMouseClicked

    private void potonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potonganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potonganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formgaji.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formgaji().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ateam;
    private javax.swing.JButton BtnRpegawai;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JButton Btnrefresh;
    private javax.swing.JComboBox<String> Cbjabatan;
    private javax.swing.JMenuItem Dpegawai;
    private javax.swing.JMenuItem Dpenggajian;
    private javax.swing.JMenuItem Dperlengkapan;
    private javax.swing.JMenuItem Dproduk;
    private javax.swing.JMenuItem Fexit;
    private javax.swing.JMenuItem Fhome;
    private javax.swing.JMenuItem Flogout;
    private javax.swing.JMenuItem Hinfo;
    private javax.swing.JTextField Nik;
    private javax.swing.JMenuItem Rpegawai;
    private javax.swing.JMenuItem Rpenggajian;
    private javax.swing.JMenuItem Rperlengkapan;
    private javax.swing.JMenuItem Rproduk;
    private javax.swing.JLabel a;
    private javax.swing.JLabel a1;
    private javax.swing.JButton b_Delete;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Update;
    private javax.swing.JTextField bonus;
    private javax.swing.JLabel c;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel f;
    private javax.swing.JLabel f1;
    private javax.swing.JTextField gaji_bersih;
    private javax.swing.JTextField gaji_pokok;
    private javax.swing.JLabel j;
    private javax.swing.JLabel j1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel l;
    private javax.swing.JTextField nama_karyawan;
    private javax.swing.JTextField potongan;
    private javax.swing.JTable table_gaji;
    private javax.swing.JTextField tunjangan;
    private javax.swing.JTextField uang_makan;
    // End of variables declaration//GEN-END:variables
}
