/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenkopi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JTextField;

/**
 *
 * @author fajarega
 */
public class formkaryawan extends javax.swing.JFrame {
    
    private DefaultTableModel tabmode;
    private void tampilpegawai(){
        Object[] baris = {"No","Id karyawan","NIK","Nama","Jenis kelamin","Tempat lahir","Tanggal lahir","Pendidikan","Tanggal masuk","Jabatan","Status","Agama","Kontak","Usia","Alamat"};
        
        tabmode = new DefaultTableModel(null,baris);
        tabmode.setRowCount(0);
         
         try {
            Statement stmt = koneksi.createStatement();
            String query = "SELECT * FROM t_karyawan";
            ResultSet rs = stmt.executeQuery(query);
            int no = 1;
            while (rs.next()){
                String id_karyawan = rs.getString("id_karyawan");
                String nik = rs.getString("nik");
                String nama = rs.getString("nama");
                String jk = rs.getString("jk");
                String tempat_lahir = rs.getString("tempat_lahir");
                String tanggal_lahir = rs.getString("tanggal_lahir");
                String pendidikan = rs.getString("pendidikan");
                String tanggal_masuk = rs.getString("tanggal_masuk");
                String jabatan = rs.getString("jabatan");
                String status = rs.getString("status");
                String agama = rs.getString("agama");
                String kontak = rs.getString("kontak");
                String usia = rs.getString("usia");
                String alamat = rs.getString("alamat");
                String[] data = {no+"",id_karyawan,nik,nama,jk,tempat_lahir,tanggal_lahir,pendidikan,tanggal_masuk,jabatan,status,agama,kontak,usia,alamat};
                no++;
                tabmode.addRow(data);
            }
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Menampilkan data GAGAL", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
         table_pegawai.setModel(tabmode);
    }
    
    Connection koneksi;
    public formkaryawan() {
        initComponents();
        koneksi = databaseconnection.getKoneksi("localhost", "3306", "root", "", "db_industri");
        tampilpegawai();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        Btnrefresh = new javax.swing.JButton();
        jToolBar2 = new javax.swing.JToolBar();
        BtnRpegawai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_pegawai = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        q = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        t = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        k = new javax.swing.JLabel();
        m = new javax.swing.JLabel();
        l = new javax.swing.JLabel();
        v = new javax.swing.JLabel();
        Id_karyawan = new javax.swing.JTextField();
        Nik = new javax.swing.JTextField();
        Nama = new javax.swing.JTextField();
        Tempat_lahir = new javax.swing.JTextField();
        Cbjk = new javax.swing.JComboBox<>();
        Cbpendidikan = new javax.swing.JComboBox<>();
        Cbjabatan = new javax.swing.JComboBox<>();
        Cbstatus = new javax.swing.JComboBox<>();
        Cbagama = new javax.swing.JComboBox<>();
        Kontak = new javax.swing.JTextField();
        Usia = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        Btn_simpan = new javax.swing.JButton();
        b_Update = new javax.swing.JButton();
        b_Delete = new javax.swing.JButton();
        b_Reset = new javax.swing.JButton();
        Tanggal_masuk = new com.toedter.calendar.JDateChooser();
        Tanggal_lahir = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Fhome = new javax.swing.JMenuItem();
        Flogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Fexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Dpegawai = new javax.swing.JMenuItem();
        Dpenggajian = new javax.swing.JMenuItem();
        Dperlengkapan = new javax.swing.JMenuItem();
        Dproduk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Rpegawai = new javax.swing.JMenuItem();
        Rpenggajian = new javax.swing.JMenuItem();
        Rperlengkapan = new javax.swing.JMenuItem();
        Rproduk = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Hinfo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Ateam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 204, 255));

        jToolBar1.setBackground(new java.awt.Color(153, 153, 153));
        jToolBar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToolBar1.setRollover(true);

        Btnrefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/002-refresh.png"))); // NOI18N
        Btnrefresh.setFocusable(false);
        Btnrefresh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Btnrefresh.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnrefreshActionPerformed(evt);
            }
        });
        jToolBar1.add(Btnrefresh);

        jToolBar2.setRollover(true);
        jToolBar1.add(jToolBar2);

        BtnRpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/24 Pixel/people-4.png"))); // NOI18N
        BtnRpegawai.setFocusable(false);
        BtnRpegawai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BtnRpegawai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BtnRpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRpegawaiActionPerformed(evt);
            }
        });
        jToolBar1.add(BtnRpegawai);

        table_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Id karyawan", "NIK", "Nama", "Jenis kelamin", "Tempat lahir", "Tanggal lahir", "Pendidikan", "Tanggal masuk", "Jabatan", "Status", "Agama", "Kontak", "Usia", "Alamat"
            }
        ));
        table_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_pegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_pegawai);

        jPanel2.setBackground(new java.awt.Color(51, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MANAGE PEGAWAI", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        a.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        a.setText("ID KARYAWAN");

        b.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        b.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        b.setText("NIK");

        c.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        c.setText("Nama");

        d.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        d.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        d.setText("Jenis Kelamin");

        f.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        f.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        f.setText("Tempat Lahir");

        q.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        q.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        q.setText("Tanggal Lahir");

        e.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        e.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        e.setText("Pendidikan Terakhir");

        t.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        t.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t.setText("Tanggal Masuk");

        h.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        h.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        h.setText("Jabatan");

        j.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        j.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        j.setText("Status");

        k.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        k.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        k.setText("Agama");

        m.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        m.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        m.setText("Kontak");

        l.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        l.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l.setText("Usia");

        v.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        v.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        v.setText("Alamat");

        Id_karyawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_karyawanActionPerformed(evt);
            }
        });

        Cbjk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Laki-laki", "Perempuan" }));

        Cbpendidikan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "SD", "SMA", "SMK", "S1", "S2", "S3" }));
        Cbpendidikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbpendidikanActionPerformed(evt);
            }
        });

        Cbjabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "General Manajer", "Direktur", "Supervisor", "HRD", "Staff", "Sales", "Buruh", "Sopir", "Security" }));

        Cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Nikah", "Belum Nikah", "Janda", "Duda" }));

        Cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "== PILIH ==", "Islam", "Kristen", "Budha", "Hindu", "Konchucu" }));

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane2.setViewportView(Alamat);

        Btn_simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/16 Pixel/add-contact.png"))); // NOI18N
        Btn_simpan.setText("Tambah");
        Btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_simpanActionPerformed(evt);
            }
        });

        b_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save-16x16.png"))); // NOI18N
        b_Update.setText("Update");
        b_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UpdateActionPerformed(evt);
            }
        });

        b_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete-16x16.png"))); // NOI18N
        b_Delete.setText("Delete");
        b_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_DeleteActionPerformed(evt);
            }
        });

        b_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        b_Reset.setText("Reset");
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(d, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(a, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(t, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tanggal_masuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Id_karyawan)
                    .addComponent(Nik, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(Nama, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(Cbjk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(104, 104, 104)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(l, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(e)
                            .addComponent(v, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tempat_lahir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Usia, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(Cbpendidikan, 0, 230, Short.MAX_VALUE)
                    .addComponent(Tanggal_lahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(k, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(h, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(123, 123, 123))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b_Update, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(b_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                            .addComponent(b_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(107, 107, 107))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(a)
                            .addComponent(h)
                            .addComponent(Id_karyawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cbjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b)
                            .addComponent(Cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(k)
                                    .addComponent(Cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m)
                                    .addComponent(Kontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_simpan)
                                    .addComponent(b_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(b_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                    .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cbjk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(d))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t)
                                    .addComponent(Tanggal_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(f)
                            .addComponent(Tempat_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q)
                            .addComponent(Tanggal_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(e)
                            .addComponent(Cbpendidikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Usia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(v))))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        jMenu1.setText("File");

        Fhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/konfigurasi_univ.png"))); // NOI18N
        Fhome.setText("Home");
        Fhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Fhome);

        Flogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/operator.png"))); // NOI18N
        Flogout.setText("Logout");
        Flogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Flogout);
        jMenu1.add(jSeparator1);

        Fexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cross.png"))); // NOI18N
        Fexit.setText("Exit");
        Fexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FexitActionPerformed(evt);
            }
        });
        jMenu1.add(Fexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        Dpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpegawai.setText("Data Pegawai");
        Dpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(Dpegawai);

        Dpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpenggajian.setText("Data Penggajian");
        Dpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpenggajianActionPerformed(evt);
            }
        });
        jMenu2.add(Dpenggajian);

        Dperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dperlengkapan.setText("Data Perlengkapan");
        Dperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DperlengkapanActionPerformed(evt);
            }
        });
        jMenu2.add(Dperlengkapan);

        Dproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dproduk.setText("Data Produk");
        Dproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DprodukActionPerformed(evt);
            }
        });
        jMenu2.add(Dproduk);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Report");

        Rpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpegawai.setText("Pegawai");
        Rpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpegawaiActionPerformed(evt);
            }
        });
        jMenu3.add(Rpegawai);

        Rpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpenggajian.setText("Penggajian");
        Rpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpenggajianActionPerformed(evt);
            }
        });
        jMenu3.add(Rpenggajian);

        Rperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rperlengkapan.setText("Perlengkapan");
        Rperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RperlengkapanActionPerformed(evt);
            }
        });
        jMenu3.add(Rperlengkapan);

        Rproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rproduk.setText("Produk");
        Rproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprodukActionPerformed(evt);
            }
        });
        jMenu3.add(Rproduk);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        Hinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        Hinfo.setText("Info");
        Hinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinfoActionPerformed(evt);
            }
        });
        jMenu4.add(Hinfo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("About");

        Ateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/mutasipegawai.png"))); // NOI18N
        Ateam.setText("Team");
        Ateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AteamActionPerformed(evt);
            }
        });
        jMenu5.add(Ateam);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void FhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FhomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        this.dispose();
    }//GEN-LAST:event_FhomeActionPerformed

    private void DperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DperlengkapanActionPerformed
        // TODO add your handling code here:
        new formperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_DperlengkapanActionPerformed

    private void RpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpenggajianActionPerformed
        // TODO add your handling code here:
        new lapgaji().show();
        this.dispose();
    }//GEN-LAST:event_RpenggajianActionPerformed

    private void RperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RperlengkapanActionPerformed
        // TODO add your handling code here:
        new lapperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_RperlengkapanActionPerformed

    private void FlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlogoutActionPerformed
        // TODO add your handling code here:
        new login().show();
        this.dispose();
    }//GEN-LAST:event_FlogoutActionPerformed

    private void FexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FexitActionPerformed

    private void DpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpegawaiActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_DpegawaiActionPerformed

    private void DpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpenggajianActionPerformed
        // TODO add your handling code here:
        new formgaji().show();
        this.dispose();
    }//GEN-LAST:event_DpenggajianActionPerformed

    private void DprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DprodukActionPerformed
        // TODO add your handling code here:
        new formproduk().show();
        this.dispose();
    }//GEN-LAST:event_DprodukActionPerformed

    private void RpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_RpegawaiActionPerformed

    private void RprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprodukActionPerformed
        // TODO add your handling code here:
        new lapproduk().show();
        this.dispose();
    }//GEN-LAST:event_RprodukActionPerformed

    private void HinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinfoActionPerformed
        // TODO add your handling code here:
        new info().show();
        this.dispose();
    }//GEN-LAST:event_HinfoActionPerformed

    private void AteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AteamActionPerformed
        // TODO add your handling code here:
        new team().show();
        this.dispose();
    }//GEN-LAST:event_AteamActionPerformed

    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed

       String id_karyawan = Id_karyawan.getText();
       String nik = Nik.getText();
       String nama = Nama.getText();
       String jk = Cbjk.getSelectedItem().toString();
       String tempat_lahir = Tempat_lahir.getText();
       java.util.Date tanggal_lahir1 = Tanggal_lahir.getDate();
       java.sql.Date tanggal_lahir = new java.sql.Date(tanggal_lahir1.getTime());
       String pendidikan = Cbpendidikan.getSelectedItem().toString();
       java.util.Date tanggal_masuk1 = Tanggal_masuk.getDate();
       java.sql.Date tanggal_masuk = new java.sql.Date(tanggal_masuk1.getTime());
       String jabatan = Cbjabatan.getSelectedItem().toString();
       String status = Cbstatus.getSelectedItem().toString();
       String agama = Cbagama.getSelectedItem().toString();
       String kontak = Kontak.getText();
       String usia = Usia.getText();
       String alamat = Alamat.getText();
       
       try{
           Statement stmt = koneksi.createStatement();
           String query = "INSERT INTO t_karyawan(id_karyawan,nik,nama,jk,tempat_lahir,tanggal_lahir,pendidikan,tanggal_masuk,jabatan,status,agama,kontak,usia,alamat)"+"VALUES('"+id_karyawan+"', '"+nik+"', '"+nama+"', '"+jk+"', '"+tempat_lahir+"', '"+tanggal_lahir+"', '"+pendidikan+"', '"+tanggal_masuk+"', '"+jabatan+"', '"+status+"', '"+agama+"', '"+kontak+"', '"+usia+"', '"+alamat+"')";
           System.out.print(query);
           int berhasil = stmt.executeUpdate(query);
           if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dimasukkan");
                tampilpegawai();
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal Dimasukkan");
                reset();
            }
             koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Pada Database");
            reset();
        }
    }//GEN-LAST:event_Btn_simpanActionPerformed

    private void b_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_DeleteActionPerformed
        // TODO add your handling code here:
        String idWhoWantToBeDelete = table_pegawai.getValueAt(baris, 1).toString();
        try {
            Statement stmt = koneksi.createStatement();
            String query = "DELETE FROM t_karyawan WHERE id_karyawan = '"+idWhoWantToBeDelete+"';";
            int berhasil = stmt.executeUpdate(query);
            if (berhasil == 1) {
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                tabmode.getDataVector().removeAllElements();
                tampilpegawai();
                reset();
            }  
            koneksi.close();
        } catch (SQLException ex){
            ex.printStackTrace();
        }
       
    }//GEN-LAST:event_b_DeleteActionPerformed

        
    public void reset(){
        Id_karyawan.setText("");
        Nik.setText("");
        Nama.setText("");
        Cbjk.setSelectedIndex(0);
        Tempat_lahir.setText("");
        Tanggal_lahir.setDate(null);
        Cbpendidikan.setSelectedIndex(0);
        Tanggal_masuk.setDate(null);
        Cbjabatan.setSelectedIndex(0);
        Cbstatus.setSelectedIndex(0);
        Cbagama.setSelectedIndex(0);
        Kontak.setText("");
        Usia.setText("");
        Alamat.setText("");
    }
    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
        reset();
    }//GEN-LAST:event_b_ResetActionPerformed
    public void EditData()
    {
       String id_karyawan = Id_karyawan.getText();
       String nik = Nik.getText();
       String nama = Nama.getText();
       String jk = Cbjk.getSelectedItem().toString();
       String tempat_lahir = Tempat_lahir.getText();
       java.util.Date tanggal_lahir1 = Tanggal_lahir.getDate();
       java.sql.Date tanggal_lahir = new java.sql.Date(tanggal_lahir1.getTime());
       String pendidikan = Cbpendidikan.getSelectedItem().toString();
       java.util.Date tanggal_masuk1 = Tanggal_masuk.getDate();
       java.sql.Date tanggal_masuk = new java.sql.Date(tanggal_masuk1.getTime());
       String jabatan = Cbjabatan.getSelectedItem().toString();
       String status = Cbstatus.getSelectedItem().toString();
       String agama = Cbagama.getSelectedItem().toString();
       String kontak = Kontak.getText();
       String usia = Usia.getText();
       String alamat = Alamat.getText();
        
        try
        {
            Statement stmt = koneksi.createStatement();
            String query = "UPDATE t_penggajian SET "+ "nik='"+nik+"',"+"nama='"+nama+"',"+"jk='"+jk+"',"+"tempat_lahir='"+tempat_lahir+"',"+"tanggal_lahir1='"+tanggal_lahir1+"',"+"tanggal_lahir='"+tanggal_lahir+"',"+"pendidikan='"+pendidikan+"',"+"tanggal_masuk1='"+tanggal_masuk1+"',"+"tanggal_masuk='"+tanggal_masuk+"',"+"jabatan='"+jabatan+"' "+"status='"+status+"',"+"agama='"+agama+"' " +"kontak='"+kontak+"',"+"usia='"+usia+"' "+"alamat='"+alamat+"',"+ "WHERE id_karyawan = '"+id_karyawan+"'";
            System.out.println(query);
            int berhasil = stmt.executeUpdate(query);
            if(berhasil == 1)
            {
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
        }
        catch (SQLException ex)
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan pada Database");
        }
    }
    private void b_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UpdateActionPerformed
    EditData();
    tampilpegawai();
    reset();
    }//GEN-LAST:event_b_UpdateActionPerformed

    private void BtnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnrefreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnrefreshActionPerformed

    private void BtnRpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_BtnRpegawaiActionPerformed
    
    int baris;
    private void table_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_pegawaiMouseClicked
        // TODO add your handling code here:
        baris = table_pegawai.getSelectedRow();
        Id_karyawan.setText(table_pegawai.getValueAt(baris,1).toString());
        Nik.setText(table_pegawai.getValueAt(baris,2).toString());
        Nama.setText(table_pegawai.getValueAt(baris,3).toString());
        Cbjk.setSelectedItem(table_pegawai.getValueAt(baris,4).toString());
        Tempat_lahir.setText(table_pegawai.getValueAt(baris,5).toString());
        
        Cbpendidikan.setSelectedItem(table_pegawai.getValueAt(baris,7).toString());
        
        Cbjabatan.setSelectedItem(table_pegawai.getValueAt(baris,9).toString());
        Cbstatus.setSelectedItem(table_pegawai.getValueAt(baris,10).toString());
        Cbagama.setSelectedItem(table_pegawai.getValueAt(baris,11).toString());
        Kontak.setText(table_pegawai.getValueAt(baris,12).toString());
        Usia.setText(table_pegawai.getValueAt(baris,13).toString());
        Alamat.setText(table_pegawai.getValueAt(baris,14).toString());
        
    }//GEN-LAST:event_table_pegawaiMouseClicked

    private void CbpendidikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbpendidikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbpendidikanActionPerformed

    private void Id_karyawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_karyawanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_karyawanActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formkaryawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formkaryawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JMenuItem Ateam;
    private javax.swing.JButton BtnRpegawai;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JButton Btnrefresh;
    private javax.swing.JComboBox<String> Cbagama;
    private javax.swing.JComboBox<String> Cbjabatan;
    private javax.swing.JComboBox<String> Cbjk;
    private javax.swing.JComboBox<String> Cbpendidikan;
    private javax.swing.JComboBox<String> Cbstatus;
    private javax.swing.JMenuItem Dpegawai;
    private javax.swing.JMenuItem Dpenggajian;
    private javax.swing.JMenuItem Dperlengkapan;
    private javax.swing.JMenuItem Dproduk;
    private javax.swing.JMenuItem Fexit;
    private javax.swing.JMenuItem Fhome;
    private javax.swing.JMenuItem Flogout;
    private javax.swing.JMenuItem Hinfo;
    private javax.swing.JTextField Id_karyawan;
    private javax.swing.JTextField Kontak;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nik;
    private javax.swing.JMenuItem Rpegawai;
    private javax.swing.JMenuItem Rpenggajian;
    private javax.swing.JMenuItem Rperlengkapan;
    private javax.swing.JMenuItem Rproduk;
    private com.toedter.calendar.JDateChooser Tanggal_lahir;
    private com.toedter.calendar.JDateChooser Tanggal_masuk;
    private javax.swing.JTextField Tempat_lahir;
    private javax.swing.JTextField Usia;
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JButton b_Delete;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Update;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JLabel e;
    private javax.swing.JLabel f;
    private javax.swing.JLabel h;
    private javax.swing.JLabel j;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JLabel k;
    private javax.swing.JLabel l;
    private javax.swing.JLabel m;
    private javax.swing.JLabel q;
    private javax.swing.JLabel t;
    private javax.swing.JTable table_pegawai;
    private javax.swing.JLabel v;
    // End of variables declaration//GEN-END:variables
}
