/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manajemenkopi;

import java.awt.Component;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author fajarega
 */
public class info extends javax.swing.JFrame {

    private Component frame;

    /**
     * Creates new form info
     */
    public info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b_Update = new javax.swing.JButton();
        bedit = new javax.swing.JButton();
        b_Delete = new javax.swing.JButton();
        brop = new javax.swing.JButton();
        bexport = new javax.swing.JButton();
        Btn_simpan = new javax.swing.JButton();
        b_Reset = new javax.swing.JButton();
        bprint = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Fhome = new javax.swing.JMenuItem();
        Flogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Fexit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Dpegawai = new javax.swing.JMenuItem();
        Dpenggajian = new javax.swing.JMenuItem();
        Dperlengkapan = new javax.swing.JMenuItem();
        Dproduk = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Rpegawai = new javax.swing.JMenuItem();
        Rpenggajian = new javax.swing.JMenuItem();
        Rperlengkapan = new javax.swing.JMenuItem();
        Rproduk = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        Hinfo = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        Ateam = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        b_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/save-16x16.png"))); // NOI18N
        b_Update.setText("Update");
        b_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_UpdateActionPerformed(evt);
            }
        });

        bedit.setBackground(new java.awt.Color(51, 204, 255));
        bedit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bedit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1491299525_Edit.png"))); // NOI18N
        bedit.setText("Edit");
        bedit.setMaximumSize(new java.awt.Dimension(281, 137));
        bedit.setMinimumSize(new java.awt.Dimension(281, 137));
        bedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditActionPerformed(evt);
            }
        });

        b_Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/delete-16x16.png"))); // NOI18N
        b_Delete.setText("Delete");
        b_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_DeleteActionPerformed(evt);
            }
        });

        brop.setBackground(new java.awt.Color(51, 204, 255));
        brop.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        brop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1491299384_trash_can.png"))); // NOI18N
        brop.setText("Delete");
        brop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bropActionPerformed(evt);
            }
        });

        bexport.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bexport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1491299694_7.png"))); // NOI18N
        bexport.setText("Export");
        bexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexportActionPerformed(evt);
            }
        });

        Btn_simpan.setText("Tambah");
        Btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_simpanActionPerformed(evt);
            }
        });

        b_Reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        b_Reset.setText("Reset");
        b_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_ResetActionPerformed(evt);
            }
        });

        bprint.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        bprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/1491300084_Print.png"))); // NOI18N
        bprint.setText("Print");
        bprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprintActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Tekan Tombol Dibawah Untuk Melihat Fungsi Masing-Masing Tombol");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(bprint, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bedit, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bexport)
                                .addComponent(brop, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b_Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(40, 40, 40)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b_Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(162, 162, 162))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bexport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bprint)
                    .addComponent(brop))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jMenu1.setText("File");

        Fhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/konfigurasi_univ.png"))); // NOI18N
        Fhome.setText("Home");
        Fhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FhomeActionPerformed(evt);
            }
        });
        jMenu1.add(Fhome);

        Flogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/operator.png"))); // NOI18N
        Flogout.setText("Logout");
        Flogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlogoutActionPerformed(evt);
            }
        });
        jMenu1.add(Flogout);
        jMenu1.add(jSeparator1);

        Fexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cross.png"))); // NOI18N
        Fexit.setText("Exit");
        Fexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FexitActionPerformed(evt);
            }
        });
        jMenu1.add(Fexit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        Dpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpegawai.setText("Data Pegawai");
        Dpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpegawaiActionPerformed(evt);
            }
        });
        jMenu2.add(Dpegawai);

        Dpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dpenggajian.setText("Data Penggajian");
        Dpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DpenggajianActionPerformed(evt);
            }
        });
        jMenu2.add(Dpenggajian);

        Dperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dperlengkapan.setText("Data Perlengkapan");
        Dperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DperlengkapanActionPerformed(evt);
            }
        });
        jMenu2.add(Dperlengkapan);

        Dproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/file-edit-16x16.png"))); // NOI18N
        Dproduk.setText("Data Produk");
        Dproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DprodukActionPerformed(evt);
            }
        });
        jMenu2.add(Dproduk);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Report");

        Rpegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpegawai.setText("Pegawai");
        Rpegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpegawaiActionPerformed(evt);
            }
        });
        jMenu3.add(Rpegawai);

        Rpenggajian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rpenggajian.setText("Penggajian");
        Rpenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RpenggajianActionPerformed(evt);
            }
        });
        jMenu3.add(Rpenggajian);

        Rperlengkapan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rperlengkapan.setText("Perlengkapan");
        Rperlengkapan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RperlengkapanActionPerformed(evt);
            }
        });
        jMenu3.add(Rperlengkapan);

        Rproduk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/report.png"))); // NOI18N
        Rproduk.setText("Produk");
        Rproduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RprodukActionPerformed(evt);
            }
        });
        jMenu3.add(Rproduk);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Help");

        Hinfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/info_1.png"))); // NOI18N
        Hinfo.setText("Info");
        Hinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HinfoActionPerformed(evt);
            }
        });
        jMenu4.add(Hinfo);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("About");

        Ateam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/mutasipegawai.png"))); // NOI18N
        Ateam.setText("Team");
        Ateam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AteamActionPerformed(evt);
            }
        });
        jMenu5.add(Ateam);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FhomeActionPerformed
        // TODO add your handling code here:
        new Home().show();
        this.dispose();
    }//GEN-LAST:event_FhomeActionPerformed

    private void DperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DperlengkapanActionPerformed
        // TODO add your handling code here:
        new formperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_DperlengkapanActionPerformed

    private void RpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpenggajianActionPerformed
        // TODO add your handling code here:
        new lapgaji().show();
        this.dispose();
    }//GEN-LAST:event_RpenggajianActionPerformed

    private void RperlengkapanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RperlengkapanActionPerformed
        // TODO add your handling code here:
        new lapperlengkapan().show();
        this.dispose();
    }//GEN-LAST:event_RperlengkapanActionPerformed

    private void FlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlogoutActionPerformed
        // TODO add your handling code here:
        new login().show();
        this.dispose();
    }//GEN-LAST:event_FlogoutActionPerformed

    private void FexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_FexitActionPerformed

    private void DpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpegawaiActionPerformed
        // TODO add your handling code here:
        new formkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_DpegawaiActionPerformed

    private void DpenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DpenggajianActionPerformed
        // TODO add your handling code here:
        new formgaji().show();
        this.dispose();
    }//GEN-LAST:event_DpenggajianActionPerformed

    private void DprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DprodukActionPerformed
        // TODO add your handling code here:
        new formproduk().show();
        this.dispose();
    }//GEN-LAST:event_DprodukActionPerformed

    private void RpegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RpegawaiActionPerformed
        // TODO add your handling code here:
        new lapkaryawan().show();
        this.dispose();
    }//GEN-LAST:event_RpegawaiActionPerformed

    private void RprodukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RprodukActionPerformed
        // TODO add your handling code here:
        new lapproduk().show();
        this.dispose();
    }//GEN-LAST:event_RprodukActionPerformed

    private void HinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HinfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HinfoActionPerformed

    private void AteamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AteamActionPerformed
        // TODO add your handling code here:
        new team().show();
        this.dispose();
    }//GEN-LAST:event_AteamActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void beditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Merubah data Lewat Form.",
    "Edit Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_beditActionPerformed

    private void bexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexportActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Meng-Export data ke bentuk Excel 2003(.Xls).",
    "Export Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bexportActionPerformed

    private void bprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprintActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Melakukan Pencetakan Data.",
    "Print Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bprintActionPerformed

    private void bropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bropActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Menghapus data dari Database.",
    "Delete Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_bropActionPerformed

    private void b_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_DeleteActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Menghapus data dari Database.",
    "Delete Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b_DeleteActionPerformed

    private void b_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_ResetActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Menghapus data pada Form.",
    "Reset",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b_ResetActionPerformed

    private void b_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_UpdateActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Mengubah data pada Database.",
    "Update Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_b_UpdateActionPerformed

    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed
    JOptionPane.showMessageDialog(frame,
    "Menyimpan data pada Database.",
    "Simpan Data",
    JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Btn_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Ateam;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JMenuItem Dpegawai;
    private javax.swing.JMenuItem Dpenggajian;
    private javax.swing.JMenuItem Dperlengkapan;
    private javax.swing.JMenuItem Dproduk;
    private javax.swing.JMenuItem Fexit;
    private javax.swing.JMenuItem Fhome;
    private javax.swing.JMenuItem Flogout;
    private javax.swing.JMenuItem Hinfo;
    private javax.swing.JMenuItem Rpegawai;
    private javax.swing.JMenuItem Rpenggajian;
    private javax.swing.JMenuItem Rperlengkapan;
    private javax.swing.JMenuItem Rproduk;
    private javax.swing.JButton b_Delete;
    private javax.swing.JButton b_Reset;
    private javax.swing.JButton b_Update;
    private javax.swing.JButton bedit;
    private javax.swing.JButton bexport;
    private javax.swing.JButton bprint;
    private javax.swing.JButton brop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
